name: printxapp
description: "A new Flutter project."

publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: ^3.7.2

dependencies:
  flutter:
    sdk: flutter
  dio: ^5.8.0+1
  # UI & Icons
  cupertino_icons: ^1.0.8

  firebase_core: ^3.12.1
  firebase_auth: ^5.5.1
  cloud_firestore: ^5.6.5
  firebase_storage: ^12.4.4
  firebase_messaging: ^15.2.4

  # State Management
  provider: ^6.1.2

  # File Handling & Image Upload
  file_picker: ^9.2.1
  image_picker: ^1.0.7

  # Payments (Razorpay)
  razorpay_flutter: ^1.3.5

  
  url_launcher: ^6.1.14
  # HTTP Requests
  http: ^1.2.1

  # Caching & Storage
  shared_preferences: ^2.2.3

  # Loading Indicators
  flutter_spinkit: ^5.2.0

  # PDF & Printing
  pdf: ^3.10.7
  printing: ^5.12.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: ^0.14.3  # Use the latest version
  flutter_lints: ^5.0.0

flutter_icons:
  android: true
  ios: true
  image_path: "./lib/assets/icon/app_icon.png"  # Path to your app icon
  adaptive_icon_background: "#ffffff"  # Background color (optional)
  adaptive_icon_foreground: "./lib/assets/icon/app_icon.png"  # Adaptive icon foreground (optional)

flutter:
  uses-material-design: true

  assets:
    - assets/images/ # Folder for images
    - assets/icons/  # Folder for icons
